export const NOTIFICATION_KINDS = {
  giveawayAvailable: "giveaway_available",
  giveawayWon: "giveaway_won",
  pollStarted: "poll_started",
  warningIssued: "warning_issued",
  warningRevoked: "warning_revoked",
  membershipApproved: "membership_approved",
  paymentReceived: "payment_received",
  eventAvailable: "event_available",
  applicationSubmitted: "application_submitted",
  giveawayEnded: "giveaway_ended",
  contributionOpen: "contribution_open",
  birthdayPost: "birthday_post",
  merchandiseOrderConfirmed: "merchandise_order_confirmed",
  eventReminder7d: "event_reminder_7d",
  eventReminder2d: "event_reminder_2d",
  rankUp: "rank_up",
  merchandiseOrderAdmin: "merchandise_order_admin",
  eventSyncFailed: "event_sync_failed",
  clubMeetingPublished: "club_meeting_published",
  commentReply: "comment_reply",
  postComment: "post_comment",
  referralCompleted: "referral_completed",
  badgeUnlocked: "badge_unlocked",
  radioVotingLastChance: "radio_voting_last_chance",
  radioVotingAvailable: "radio_voting_available",
  radioVotingNewCycle: "radio_voting_new_cycle",
  postPendingReview: "post_pending_review",
  postApproved: "post_approved",
  postRejected: "post_rejected",
  mention: "mention",
  profileChangePending: "profile_change_pending",
  profileChangeApproved: "profile_change_approved",
  profileChangeRejected: "profile_change_rejected",
  introIncompleteReminder: "intro_incomplete_reminder",
  introSteckbriefComplete: "intro_steckbrief_complete",
} as const;

export type NotificationKind = (typeof NOTIFICATION_KINDS)[keyof typeof NOTIFICATION_KINDS];
