import { EMAIL_SALUTATION_PLACEHOLDER } from "@/lib/email/salutation-block";

export const EMAIL_TEMPLATE_KEYS = {
  membershipApplicationReceived: "membership_application_received",
  membershipApplicationAdminNotify: "membership_application_admin_notify",
  membershipPaymentReminder: "membership_payment_reminder",
  membershipContributionNewYear: "membership_contribution_new_year",
  membershipFormInvite: "membership_form_invite",
  membershipReferralInvite: "membership_referral_invite",
  membershipReferralReminder: "membership_referral_reminder",
  giveawayEndedAdminNotify: "giveaway_ended_admin_notify",
  giveawayWinnerCongrats: "giveaway_winner_congrats",
  membershipApprovedWelcome: "membership_approved_welcome",
  clubMeetingReminder: "club_meeting_reminder",
  appAccessSetup: "app_access_setup",
  passwordReset: "password_reset",
  appSignupReminder: "app_signup_reminder",
  appInactiveReminder: "app_inactive_reminder",
  referralAbuseAdminNotify: "referral_abuse_admin_notify",
  liveSessionInvite: "live_session_invite",
  liveSessionReminder: "live_session_reminder",
  memberLoginEmailChanged: "member_login_email_changed",
} as const;

export type EmailTemplateKey = (typeof EMAIL_TEMPLATE_KEYS)[keyof typeof EMAIL_TEMPLATE_KEYS];

const personFacingSalutation = [EMAIL_SALUTATION_PLACEHOLDER] as const;

/** Signatur wird automatisch angehängt — keine Platzhalter in Vorlagen nötig. */
export const TEMPLATE_PLACEHOLDERS: Record<
  EmailTemplateKey,
  { key: string; label: string }[]
> = {
  [EMAIL_TEMPLATE_KEYS.membershipApplicationReceived]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "last_name", label: "Nachname" },
    { key: "applicant_name", label: "Vollständiger Name" },
    { key: "email", label: "E-Mail Antragsteller" },
    { key: "fee_eur", label: "Beitrag (z. B. 15,00 EUR)" },
    { key: "bank_account_holder", label: "Kontoinhaber / Empfänger" },
    { key: "bank_iban", label: "IBAN" },
    { key: "bank_bic", label: "BIC" },
    { key: "bank_name", label: "Bank" },
    { key: "bank_reference", label: "Verwendungszweck (Mitgliedsbeitrag / Vorname Nachname)" },
  ],
  [EMAIL_TEMPLATE_KEYS.membershipApplicationAdminNotify]: [
    { key: "admin_first_name", label: "Vorname Admin (Empfänger)" },
    { key: "applicant_name", label: "Name Antragsteller" },
    { key: "email", label: "E-Mail Antragsteller" },
    { key: "submitted_at", label: "Antragsdatum + Uhrzeit" },
    { key: "application_id", label: "Antrags-ID" },
    { key: "application_admin_url", label: "Link Antragsdialog (Admin)" },
    { key: "admin_applications_url", label: "Link Mitgliederliste (Admin)" },
  ],
  [EMAIL_TEMPLATE_KEYS.membershipPaymentReminder]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "last_name", label: "Nachname" },
    { key: "applicant_name", label: "Vollständiger Name" },
    { key: "email", label: "E-Mail" },
    { key: "fee_eur", label: "Beitrag (z. B. 15,00 EUR)" },
    { key: "fee_paid_eur", label: "Bereits gezahlt" },
    { key: "fee_open_eur", label: "Offener Betrag" },
    { key: "membership_period", label: "Beitragszeitraum" },
    { key: "bank_account_holder", label: "Kontoinhaber" },
    { key: "bank_iban", label: "IBAN" },
    { key: "bank_bic", label: "BIC" },
    { key: "bank_name", label: "Bank" },
    { key: "bank_reference", label: "Verwendungszweck" },
  ],
  [EMAIL_TEMPLATE_KEYS.membershipContributionNewYear]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "last_name", label: "Nachname" },
    { key: "contribution_year", label: "Beitragsjahr (z. B. 2027)" },
    { key: "fee_eur", label: "Jahresbeitrag" },
    { key: "due_date", label: "Fällig ab" },
    { key: "payment_deadline", label: "Zahlungsfrist" },
    { key: "payment_reference", label: "Verwendungszweck (Mitgliedsbeitrag / Vorname Nachname)" },
    { key: "open_contributions_block", label: "Hinweis offene Vorjahre (oder leer)" },
    { key: "bank_account_holder", label: "Kontoinhaber" },
    { key: "bank_iban", label: "IBAN" },
  ],
  [EMAIL_TEMPLATE_KEYS.membershipFormInvite]: [
    { key: "greeting_name", label: "Anrede (z. B. Vorname nach „Hey“)" },
    { key: "application_link", label: "Link zum Antragsformular" },
    { key: "fee_eur", label: "Beitrag (z. B. 15,00 EUR)" },
  ],
  [EMAIL_TEMPLATE_KEYS.membershipReferralInvite]: [
    { key: "recipient_first_name", label: "Vorname Empfänger/in" },
    { key: "sender_name", label: "Name Werber/in" },
    { key: "application_link", label: "Link zum Antragsformular" },
  ],
  [EMAIL_TEMPLATE_KEYS.membershipReferralReminder]: [
    { key: "recipient_first_name", label: "Vorname Empfänger/in" },
    { key: "sender_name", label: "Name Werber/in" },
    { key: "application_link", label: "Link zum Antragsformular" },
  ],
  [EMAIL_TEMPLATE_KEYS.giveawayEndedAdminNotify]: [
    { key: "giveaway_title", label: "Titel Gewinnspiel" },
    { key: "giveaway_admin_url", label: "Link zur Auslosung (Admin)" },
  ],
  [EMAIL_TEMPLATE_KEYS.giveawayWinnerCongrats]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname Gewinner" },
    { key: "giveaway_title", label: "Titel Gewinnspiel" },
    { key: "prize_name", label: "Preisname" },
  ],
  [EMAIL_TEMPLATE_KEYS.membershipApprovedWelcome]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "membership_number", label: "Mitgliedsnummer" },
    { key: "setup_url", label: "Link Zugang einrichten" },
    { key: "invite_url", label: "Link Passwort setzen (Alias)" },
  ],
  [EMAIL_TEMPLATE_KEYS.clubMeetingReminder]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "meeting_title", label: "Titel Treffen" },
    { key: "meeting_date", label: "Datum & Uhrzeit" },
    { key: "meeting_location", label: "Ort" },
    { key: "meeting_url", label: "Link zur Treffen-Seite" },
    { key: "cost_hint", label: "Hinweis zu Kosten (oder leer)" },
  ],
  [EMAIL_TEMPLATE_KEYS.appAccessSetup]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "setup_url", label: "Link Zugang einrichten" },
  ],
  [EMAIL_TEMPLATE_KEYS.passwordReset]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "reset_url", label: "Link Passwort zurücksetzen" },
  ],
  [EMAIL_TEMPLATE_KEYS.appSignupReminder]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "setup_url", label: "Link Zugang einrichten" },
  ],
  [EMAIL_TEMPLATE_KEYS.appInactiveReminder]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "app_url", label: "Link zur Fanclub App" },
  ],
  [EMAIL_TEMPLATE_KEYS.referralAbuseAdminNotify]: [
    { key: "admin_first_name", label: "Vorname Admin (Empfänger)" },
    { key: "referrer_name", label: "Name Werber/in" },
    { key: "referrer_email", label: "E-Mail Werber/in" },
    { key: "reasons_text", label: "Verdachtsgründe" },
    { key: "sends_list", label: "Einladungs-Liste (Text)" },
    { key: "review_url", label: "Link Admin-Prüfung" },
  ],
  [EMAIL_TEMPLATE_KEYS.liveSessionInvite]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "session_title", label: "Titel der Live-Session" },
    { key: "session_date", label: "Datum & Uhrzeit" },
    { key: "session_url", label: "Link zur Live-Seite" },
    { key: "calendar_url", label: "Link Kalender (.ics)" },
  ],
  [EMAIL_TEMPLATE_KEYS.liveSessionReminder]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "session_title", label: "Titel der Live-Session" },
    { key: "session_date", label: "Datum & Uhrzeit" },
    { key: "session_time", label: "Uhrzeit (kurz)" },
    { key: "session_url", label: "Link zur Live-Seite" },
    { key: "calendar_url", label: "Link Kalender (.ics)" },
  ],
  [EMAIL_TEMPLATE_KEYS.memberLoginEmailChanged]: [
    ...personFacingSalutation,
    { key: "first_name", label: "Vorname" },
    { key: "new_email", label: "Neue Login-E-Mail" },
    { key: "old_email", label: "Bisherige E-Mail" },
  ],
};
